export const GET_BOT_MESSAGE = 'GET_BOT_MESSAGE';
export const APPEND_MESSAGE = 'APPEND_MESSAGE';
export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';
export const SET_LOCAL_STORAGE = 'SET_LOCAL_STORAGE';
export const GET_LOCAL_STORAGE = 'GET_LOCAL_STORAGE';
